### ISSUE TITLE
How to use JobConfigurationQuery struct?

### ISSUE THREAD

**Issue by opensourcegeek** [Byron/google-apis-rs#192] opened 2018-06-06 10:39 UTC
I'm looking to run a "query" and save result to another table. So far I can see JobConfigurationQuery struct has field to set destination table. However when you go through the central hub -> jobs -> query method it accepts only QueryRequest struct which doesn't have an option to set destination table. How do I go about running query and saving result to another table? Thanks for the help.

**Comment by opensourcegeek** [comment] 2018-06-06 16:22
So I was just poking around,

```rust
let key = service_account_key_from_file(&"secrets.json".to_string()).expect("Cannot auth gcp");
    let service_account_access = ServiceAccountAccess::new(key,
                                                           hyper::Client::with_connector(
                                                               hyper::net::HttpsConnector::new(
                                                                   hyper_rustls::TlsClient::new()
                                                               )
                                                           )
    );
    let mut hub = Bigquery::new(
        hyper::Client::with_connector(
        hyper::net::HttpsConnector::new(
                    hyper_rustls::TlsClient::new()
                )
            ),
service_account_access);
    let mut t = TableReference::default();
    t.project_id = Some("poc".to_string());
    t.dataset_id = Some("sample".to_string());
    t.table_id = Some("test2".to_string());

    let mut j = Job::default();
    let mut j_config = JobConfiguration::default();
    let mut j_config_query = JobConfigurationQuery::default();
    j_config_query.query = Some("select count(*) from sample.sample where dateTime between timestamp('2018-06-01 00:00:00') and timestamp('2018-06-01 23:59:00')".to_string());
    j_config_query.destination_table = Some(t);

    j_config.query = Some(j_config_query);
    j.configuration = Some(j_config);
    let ins_job = hub.jobs().insert(j, "poc");
    // ins_job.doit() is private.... unlike other methods extract, list...
```
In the code above I cannot insert this as a job, is there a reason why doit() is private in JobInsertCall? And mainly is this the right approach?

**Comment by Byron** [comment] 2018-06-10 15:45
Thanks for taking the time to post here, and sorry for the late reply!

This is likely the same issue as described in #191, which also contains a link to [a possible local fix](https://github.com/faradayio/google-apis-rs/commit/7c314e54e061d2f1c42f282388b48c6310abf44a).
Alternatively, you could copy the files from the 'gen' folder in this repository and let `cargo` refer to them instead, after you have fixed the visibility of the required function.

Right now I am unable to invest time here, but but be very happy for PRs that fix the logic issue causing this problem.

**Comment by Byron** [comment] 2021-04-15 02:37
I am closing this issue as since then a lot has changed. All crates are now `async`, available as v2.0 on crates.io and build against the latest API spec.
Please let me know in the comments if the issue is still relevant though.

**Closed by Byron** 2021-04-15 02:37 UTC
Labels: acknowledged, help wanted

**Comment by vlushn** [comment] 2021-11-08 22:05
This issue still exists as `.doit()` is still private. The impact is that you cannot start an asynchronous query job and are forced to use REST API that returns json.

**Comment by Byron** [comment] 2021-11-08 23:44
Thanks for the pointer. Does this mean that if you locally patch the crate, maybe using `cargo-patch` even, making `doit()` public in the process, everything works fine for you?

If so, I think it should be straightforward to adjust the generator to apply this change to all crates.

**Comment by vlushn** [comment] 2021-11-09 08:39
Yes, it returns and parses the job just fine 👍 Here is what I changed (minus regenerated noise): https://github.com/vlushn/google-apis-rs/commit/a42b5d41f212bf5822d318ef5f988b1026a64342 

If you want me to test other APIs then I can give it a shot but not this week.

**Comment by Byron** [comment] 2021-11-09 09:27
Great, and the change looks like it could go into the generator without problems. The problem with any change to the JSON is that it would be overwritten the next time these are updated.
Fortunately it's possible to setup overrides which in theory could overwrite arbitrary values in such JSON to be much like a patch. There should be examples of that somewhere as well. 
That's all I remember 😅.

> If you want me to test other APIs then I can give it a shot but not this week.

All help is much appreciated, thanks a million.
