### ISSUE TITLE
Consistent build failures

### ISSUE THREAD

**Issue by programble** [Byron/google-apis-rs#148] opened 2016-02-21 00:08 UTC
I'm getting intermittent build failures locally and consistent build failures on Travis CI:

```
failed to run custom build command for `google-gmail1 v0.1.11+20151214`
Process didn't exit successfully: `/home/travis/build/programble/fresh/target/debug/build/google-gmail1-75b8106a78a393ea/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'assertion failed: (self.right != self.left)', /home/travis/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.29.0/src/print/pp.rs:447
```

https://travis-ci.org/programble/fresh/jobs/110677771

**Comment by Byron** [comment] 2016-02-21 13:01
To me it looks like an issue with the build script, which essentially runs the serde-precompiler. What do you think I can do to help with it ?

**Comment by programble** [comment] 2016-02-21 18:55
I haven't checked the versions of the build dependencies. Since this just started happening, it seems like one of them maybe had a patch bump that broke things?

**Comment by reem** [comment] 2016-02-26 02:35
I am seeing this too, anything I can do to help?

**Comment by Byron** [comment] 2016-02-26 06:41
I believe this is related to https://github.com/Byron/yup-oauth2/issues/16 , which in turn goes back to https://github.com/serde-rs/syntex/issues/33 .
Currently I am just linking up the issues, maybe @erickt will be able to put the pieces together.
Usually, when issues arise in syntex land, I am totally lost.

**Comment by programble** [comment] 2016-03-05 20:44
Workaround:

```toml
[dependencies]
serde = "0.6.0"
serde_json = "0.6.0"

[build-dependencies]
syntex = "=0.28.0"
serde_codegen = "=0.6.13"
```

Anything later than `serde_codegen 0.6.13` is broken.

**Comment by softprops** [comment] 2016-03-28 04:27
Is there a suggested version of this library to use to avoid this issue. I tried the suggestion above and my build still fails with

```
Process didn't exit successfully: `/source/target/debug/build/google-pubsub1-2ce61d1019a8c245/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'assertion failed: (self.right != self.left)', /root/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/print/pp.rs:447
```

**Comment by Byron** [comment] 2016-03-28 07:01
@softprops Something you should be able to do is to just pull this repository, look into the `gen/google-pubsub1` directory, and alter the cargo.toml to the workaround posted by @programble . It's quite a theory though because when I tried these numbers, I would get plenty incompatible types within serde_json 0.6.0. Maybe I am missing something though.
It's quite annoying that most of the APIs provided here are currently broken due to this issue, and I am hoping @erickt will have some time to look into the underlying problem at some point. Also I hope to have some more time soon to dig in properly, after all the workaround is supposed to work and I'd love to see it used here as well.

**Comment by programble** [comment] 2016-03-30 23:14
This is the patch I applied, but I've only actually generated and used `google-gmail1` with it:

```patch
From 79a8e2c9d36b52e4020bb7851a11b8b0cf42ea04 Mon Sep 17 00:00:00 2001
From: Curtis McEnroe <programble@gmail.com>
Date: Sat, 5 Mar 2016 16:03:40 -0500
Subject: [PATCH] Pin serde_codegen to 0.6.13

---
 src/mako/Cargo.toml.mako | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/src/mako/Cargo.toml.mako b/src/mako/Cargo.toml.mako
index f124f8d..cdd73be 100644
--- a/src/mako/Cargo.toml.mako
+++ b/src/mako/Cargo.toml.mako
@@ -29,16 +29,16 @@ name = "${util.program_name()}"
 hyper = "0.7"
 ## Must match the one hyper uses, otherwise there are duplicate similarly named `Mime` structs
 mime = "0.1.0"
-serde = ">= 0.7.0"
-serde_json = ">= 0.7.0"
+serde = "0.6.0"
+serde_json = "0.6.0"
 yup-oauth2 = ">= 0.5.4"
 % for dep in cargo.get('dependencies', list()):
 ${dep}
 % endfor

 [build-dependencies]
-syntex = { version = ">= 0.23" }
-serde_codegen = { version = ">= 0.6" }
+syntex = "=0.28.0"
+serde_codegen = "=0.6.13"

 % if make.depends_on_suffix is not None:

--
2.7.2
```

**Comment by Byron** [comment] 2016-04-10 12:26
Thanks @programble , I finally managed to get it to compile as well, and am currently publishing new versions to crates.io.
To me it seems serde is breaking apart, and I admit I don't fully understand what's going on there. For some reason, I had to adjust yup-oauth to use the same serde as google-apis-rs, otherwise it wouldn't compile. Interestingly, `yup-oauth2` doesn't build standalone anymore, but does so when used by `google-apis-rs`. 
Another issue I encountered is that `hyper::header::[authorization]::Scheme` is not implemented for `yup-oauth::Scheme` when used in `google-apis-rs`, but seems to have no problem when used within `yup-oauth2`. Thus I ended up just using the `hyper:0.8` `Bearer` header type as a workaround.

It's quite interesting that serialization/deserialization in Rust still seems to be somewhat difficult to achieve and to keep stable, at least from my experience so far.

In any case, I will keep the issue open as the root cause of this is not yet fixed.

**Comment by programble** [comment] 2016-04-10 20:43
Good to see new versions released finally!

**Comment by softprops** [comment] 2016-04-10 20:54
Great! I'm going to give this lib a second spin

**Comment by Byron** [comment] 2016-05-20 16:38
Please note that for now you can compile with nightly to workaround the syntex problem. I am using a line like this to do that:

```bash
make drive3-cli-cargo ARGS=build --no-default-features --features=nightly
```

Also a new authentication flow was added and set as default, which will make APIs like `drive3` and `calendar` work out of the box.

**Comment by Byron** [comment] 2016-05-28 15:37
A PR is on the way to fix this issue on stable as well: https://github.com/serde-rs/syntex/pull/47

**Comment by Byron** [comment] 2016-06-20 04:24
Thanks to the merge upstream this issue is now fixed for google-apis-rs as well. Please run something like `make youtube3-cli-cargo ARGS=update` to get the latest version of `serde`.

For completeness, I link the [related issue](https://github.com/rust-lang/rust/pull/33934#issuecomment-226700470) in rust's libsyntax.

**Closed by Byron** 2016-06-20 04:24 UTC
Labels: acknowledged
