### ISSUE TITLE
Gmail API outdated

### ISSUE THREAD

**Issue by RagibHasin** [Byron/google-apis-rs#258] opened 2020-10-04 04:20 UTC
Is gmail API not supported anymore? Can I help to get it supported somehow?

**Comment by Byron** [comment] 2020-10-04 05:22
[By the looks of it](https://github.com/Byron/google-apis-rs/blob/4c4c6694410272c1e09ea4185a84c6b0cb0cde96/etc/api/shared.yaml#L20:L21) it was blacklisted because of a name clash with our [Delegate trait](https://github.com/Byron/google-apis-rs/blob/4c4c6694410272c1e09ea4185a84c6b0cb0cde96/src/rust/api/cmn.rs#L132:L132). The issue is long standing, and could be fixed by using fully qualified names for the types we import ourselves instead of a blanket import [here](https://github.com/Byron/google-apis-rs/blob/4c4c6694410272c1e09ea4185a84c6b0cb0cde96/src/mako/api/lib.rs.mako#L67:L67) and/or [here](https://github.com/Byron/google-apis-rs/blob/4c4c6694410272c1e09ea4185a84c6b0cb0cde96/src/mako/cli/lib/engine.mako#L34:L34).

Your help would be much appreciated for sure - the main entry point is the make file and you can see what it can do by running `make`, a lot of that is described [in the README](https://github.com/Byron/google-apis-rs/blob/master/README.md#L14:L14).

Last but not least, once the imports are fixed, you probably want to run `make update-json` to fetch the latest API descriptions - I can't do that anymore unfortunately due to Google being blocked here.

**Comment by RagibHasin** [comment] 2020-10-04 06:50
Okay, I'll look into it then

**Comment by petrosagg** [comment] 2020-12-17 13:44
I looked into fixing this issue but I'm not sure what you mean by using fully qualified names. Even before the blanket import was introduced (7a44b3eae14e386ba634ace358c713324a6a0395) there was an explicit mention of the `Delegate` trait.

Unless I'm missing something, the clash will still happen unless one of the following happens:

* All Gmail structs are exported through a submodule (perhaps named `gmail` or `api`)
* `cmn::{...}` items are re-exported through a separate submodule (perhaps named `cmn`)
* The `Delegate` trait of this crate is renamed
* The `Delegate` trait of Gmail is renamed (maybe to `GmailDelegate`?)

Is this correct? And if yes, what path do you prefer? IMO creating a clean namespace for whatever Google comes up with sounds like the best approach to avoid collisions. I don't know if you're willing to do such a breaking change though. Happy to proceed either way

**Comment by Byron** [comment] 2020-12-18 03:28
Thanks, @petrosagg , for looking into it!

I agree with your assessment, and believe a breaking change can't be avoided one way or another in order to fix this. The only way out would be renaming clashing types, but that might be harder to implement.

I would probably avoid renaming `Delegate` as it's too specific of a solution, there are other name clashes in other APIs.

While embracing a breaking change as an option I think one should go with whatever is easiest to implement.

Once a PR is submitted I am happy to provide all the support I can whilst having forgotten most of the codebase 😅.

**Comment by Byron** [comment] 2021-04-15 01:56
This issue should be fixed [with v2.0.4](https://crates.io/crates/google-gmail1) - please have a look. It's now `async`, too.

Even though I close this issue, please feel free to let me know in the comments if something else needs fixing.

**Closed by Byron** 2021-04-15 01:56 UTC
Labels: Q&A, acknowledged, help wanted
