### ISSUE TITLE
Compile failed!

### ISSUE THREAD

**Issue by MrMic** [Byron/google-apis-rs#517] opened 2024-08-12 07:36 UTC
```
   Compiling chrono v0.4.38
   Compiling hyper-rustls v0.25.0
   Compiling yup-oauth2 v9.0.0
   Compiling hyper-rustls v0.24.2
   Compiling google-apis-common v6.0.4
   Compiling yup-oauth2 v8.3.2
   Compiling google-calendar3 v5.0.5+20240328
   Compiling google-clis-common v6.0.0
   Compiling google-calendar3-cli v5.0.4+20240223
error[E0308]: mismatched types
    --> /home/mic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/google-calendar3-cli-5.0.4+20240223/src/main.rs:3553:13
     |
3552 |         let auth = oauth2::InstalledFlowAuthenticator::with_client(
     |                    ----------------------------------------------- arguments to this function are incorrect
3553 |             secret,
     |             ^^^^^^ expected `ApplicationSecret`, found `yup_oauth2::types::ApplicationSecret`
     |
     = note: `yup_oauth2::types::ApplicationSecret` and `ApplicationSecret` have similar names, but are actually distinct types
note: `yup_oauth2::types::ApplicationSecret` is defined in crate `yup_oauth2`
    --> /home/mic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yup-oauth2-8.3.2/src/types.rs:145:1
     |
145  | pub struct ApplicationSecret {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: `ApplicationSecret` is defined in crate `yup_oauth2`
    --> /home/mic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yup-oauth2-9.0.0/src/types.rs:145:1
     |
145  | pub struct ApplicationSecret {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: perhaps two different versions of crate `yup_oauth2` are being used?
note: associated function defined here
    --> /home/mic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yup-oauth2-9.0.0/src/authenticator.rs:215:12
     |
215  |     pub fn with_client<C>(
     |            ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `google-calendar3-cli` (bin "calendar3") due to 1 previous error
error: failed to compile `google-calendar3-cli v5.0.4+20240223`, intermediate artifacts can be found at `/tmp/cargo-installXLz1DM`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
Can u fix that?

Rgds,

**Comment by Byron** [comment] 2024-08-12 07:58
A dupe of #516, please take a look at [my answer](https://github.com/Byron/google-apis-rs/issues/516#issuecomment-2282648267) there.

**Closed by Byron** 2024-08-12 07:58 UTC
Labels: duplicate
