### ISSUE TITLE
Cannot pull older version of the library using newer version of cargo for musl target

### ISSUE THREAD

**Issue by opensourcegeek** [Byron/google-apis-rs#176] opened 2017-08-07 16:29 UTC
cargo --version
cargo 0.20.0 (a60d185c8 2017-07-13)

Downloading google-bigquery2 v1.0.0+20160903
  error: unable to get packages from source
Caused by:
  failed to verify the checksum of `google-bigquery2 v1.0.0+20160903`

Any ideas please?

**Comment by Byron** [comment] 2017-09-28 11:53
I am unable to reproduce this issue - when I tried it locally it seemed to build just fine. Maybe it's fixed by now?
In any case, I don't think it has to do with this project, so I would like to close the issue knowing that it's tracked elsewhere. Thanks for your understanding.

<details>

```
cargo --version
cargo 0.21.0 (5b4b8b2ae 2017-08-12)
```

**Closed by Byron** 2017-09-28 11:53 UTC
