### ISSUE TITLE
Support autoloading the credentials from the environment

### ISSUE THREAD

**Issue by mdaffin** [Byron/google-apis-rs#186] opened 2018-02-02 15:47 UTC
Most google cloud client libraries and tools support autoloading credentials from the environment. This makes it easier to use these tools as you only have to set up the auth once (or not at all if on a google cloud instance or app engine). 

This process looks for the credentials in the following locations, returning the first one that it finds.

1. Load from file pointed to be the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
1. Load from `~/${CLOUDSDK_CONFIG:-.config/gcloud}/application_default_credentials.json`
1. Load from appengine api
1. Load from the google cloud metadata service on a gce instance

In addition to this the json file from the first two can either be a `service_account` or a `authorized_user` type. Both of these have different structures, for the `service_account`:

```json
{
  "type": "service_account",
  "project_id": "",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "",
  "token_uri": "",
  "auth_provider_x509_cert_url": "",
  "client_x509_cert_url": ""
}
```
And for the `authotized_user`:

```json
{
  "client_id": "",
  "client_secret": "",
  "refresh_token": "",
  "type": "authorized_user"
}

```

Currently only the `service_account` is supported by the `yup_oauth2` library. Typically the `service_account` is the type you would download from a service account on the google console and set up via the `GOOGLE_APPLICATION_CREDENTIALS` environment variable, so that method is the easiest to get working.

Method 2, loading from `~/${CLOUDSDK_CONFIG:-.config/gcloud}/application_default_credentials.json` typically takes the form of the `authorized_user` and can be created by running `gcloud auth application-default login`. Once `authorized_user` type is supported this should also be trivial to add.

Method 3 I have not looked into much detail yet.

Method 4 is loaded from the google metadata api which is basically a http request to `http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token` on a google cloud instance with the header `Metadata-Flavor: Google` and returns an `Bearer` typed `access_token`:

```json
{
  "access_token":"",
  "expires_in":2687,
  "token_type":"Bearer"
}
```

It would make this library much easier to use if we supported this type of autoloading the credentials. I have created a [demo application](https://github.com/mdaffin/gcp-auth-example/blob/master/src/main.rs) that shows how to load the first two methods in a very hacky way and will take a look at the last two at some point.

This is blocked by two main issues,

1. yup_oauth2 does not support `authorized_user` tokens
2. there is no rust api around the compute metadata

and potentially more issues with google compute engine.

**Comment by mdaffin** [comment] 2018-02-02 17:14
Looking at things in a bit more detail it looks like the `authorized_user` structure I listed above is [embellished](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/oauth2/credentials.py#L158-L164) with `scopes` and the `token_uri` to form an oauth2 `refresh_token`. But this is still not an access token and `yup_oauth2` seems to only support access tokens.

**Comment by Byron** [comment] 2018-02-09 10:27
@mdaffin Thanks a lot for the research! I am also CCing @dermesser , who is now maintaining `yup-oauth2` and who might have an idea or two about additional flows.
Regarding the additional places to look for credentials/secrets: I believe for the CLIs such a thing can and probably should be implemented. Such functionality is well-suited for the `cmn.rs` file, which is shared by all CLIs, along with probably minor adjustments to the CLI code generator.
It might also be a good way to get started contributing to the project.

**Comment by mdaffin** [comment] 2018-02-11 23:02
I was thinking about integrating the auth into the APIs and leveraging it in the CLIs. This was external applications can also take advantage of the established auth methods without having to rewrite them again.

Unfortunately, I do not have the time at the moment to look at this in much more detail, this was done as part of a viability study on a project I want to start working on in the near future. I was hoping to get the ball rolling and discuss solutions a bit before then. Right now I have a few things I need to finish up before I can start working on implementations.

My main concern at the moment is a potentially breaking change required to `ServiceAccountKey` to support refresh tokens. Is it worth raising an issue on that repo or discuss things here first?

**Comment by dermesser** [comment] 2018-02-18 17:27
for what it's worth, I opened dermesser/yup-oauth2#44 a couple months back, but didn't get around to implementing it.

But if we do talk about implementing support for this, and that's what I take this issue to be about, let's see what's actually blocking:

1. authorized_user tokens are not supported: I believe this token type is already used, but exclusively for refreshing other types of tokens (https://github.com/dermesser/yup-oauth2/blob/master/src/refresh.rs). Given that the code is already there, it should be possible to create a new flow (or implementation of `GetToken`) based on this.
2. This isn't really a blocker as I understand it, because the API is an HTTP endpoint that you can call, or files you can read. For the appengine API, we obviously should try to avoid circular dependencies... :-)

In any case, this issue is better discussed on dermesser/yup-oauth2, as @Byron did a good job separating the logic.

**Comment by Byron** [comment] 2021-04-15 02:37
I am closing this issue as since then a lot has changed. All crates are now `async`, available as v2.0 on crates.io and build against the latest API spec.
Please let me know in the comments if the issue is still relevant though.

**Closed by Byron** 2021-04-15 02:37 UTC
Labels: acknowledged, help wanted

**Comment by migel** [comment] 2021-04-16 01:23
the `authotized_user` type of json credentials is still not supported.

```json
{
  "client_id": "",
  "client_secret": "",
  "refresh_token": "",
  "type": "authorized_user"
}
```

**Comment by Byron** [comment] 2021-04-16 01:40
That may be, but wouldn't this be entirely on the side of [`yup-oauth2`](https://github.com/dermesser/yup-oauth2)?
