### ISSUE TITLE
Allow usage of api key for api calls that do not require oauth

### ISSUE THREAD

**Issue by e00E** [Byron/google-apis-rs#172] opened 2017-06-24 11:18 UTC
Some api calls do not require any user authentication and should work with just an api key without requiring oauth (https://support.google.com/googleapi/answer/6158857?hl=en).

For example I can query a public youtube playlist with curl:
```
curl -i -G -d "playlistId=PLMHbQxe1e9Mnnqj3Hs1hRDUXFEK-TgCnz&maxResults=3&part=contentDetails&key={my api key}" https://www.googleapis.com/youtube/v3/playlistItems
```
I was unable to do the same thing using `youtube3-cli` or with just the `youtube3` crate. Apologies if I simply missed it in the documentation.

**Comment by Byron** [comment] 2017-06-25 13:36
I think the problem is that most methods will want some sort of authentication right now, despite of that truly needed or not when an API key is used.
However, if providing some form of authentication against a user account is at all acceptable, it should always be possible to provide a key as additional parameter, [as specified in the docs](http://byron.github.io/google-apis-rs/google_youtube3_cli/playlists_list/) (search for 'api key' there). 

I think one way to go about this was to add logic to the generator to check for the existence of the 'key' param and make authentication optional in that case.

**Comment by Byron** [comment] 2021-04-15 02:38
I am closing this issue as since then a lot has changed. All crates are now `async`, available as v2.0 on crates.io and build against the latest API spec.
Please let me know in the comments if the issue is still relevant though.

**Closed by Byron** 2021-04-15 02:38 UTC
Labels: acknowledged

**Comment by JohnnyCrazy** [comment] 2022-08-31 13:56
I'm interested in using the youtube API just for searching and getting video data.

Is it correct that it's not possible to use the library without any kind of oauth2 authentication? Ideally, I just want to use the static API key.

**Comment by Byron** [comment] 2022-09-01 00:10
> Is it correct that it's not possible to use the library without any kind of oauth2 authentication? Ideally, I just want to use the static API key.

I think it's still not possible unless [`yup-oauth2`](https://crates.io/crates/yup-oauth2) provides this mechanism you are looking for.

**Comment by csos95** [comment] 2024-05-16 08:49
I'm writing an app now that uses oauth tokens to import user subscriptions and then an api key for everything else.

I found out that the youtube api still works if you pass an invalid authorization header (in this case `Authorization: Bearer `) along with the `key` query parameter for the api key.
So you can create a `YouTube` instance with an empty string for the auth and then add your api key to each api call with the `param` method.

I looked through some of the other google api references and they all had the `key` parameter as an option in the api explorer, so I assume it's standard for all of them to support it.

(related issues mentions for discoverability) #244 #251
