### ISSUE TITLE
google_firestore1_beta1::ProjectDatabaseDocumentRunQueryCall::doit() has incorrect return type

### ISSUE THREAD

**Issue by cpick** [Byron/google-apis-rs#220] opened 2019-03-14 21:17 UTC
The Firestore discovery document claims that `runQuery()` returns a `RunQueryResponse` object when in fact it returns an array of them.

In [a branch](https://github.com/cpick/google-apis-rs/tree/run-query-fix) in my fork I've 
wrapped `google_firestore1_beta1::ProjectDatabaseDocumentRunQueryCall::doit()`s return type in a `Vec` to reflect this reality.

This works for now, but since it's the change is to generated code it will be erased on the next re-generation.  Is there a way for me to fix this permanently?  If so I'll submit a pull request.

**Comment by Byron** [comment] 2019-07-05 02:32
Sorry for the late reply!

It's odd indeed, as [the source for the code generation](https://github.com/Byron/google-apis-rs/blob/7a44b3eae14e386ba634ace358c713324a6a0395/etc/api/firestore/v1/firestore-api.json#L2442) does claim what's returned is an object.
This would signal the issue is in the JSON schema.

It's possible to create an [overrides file like this one](https://github.com/Byron/google-apis-rs/blob/7a44b3eae14e386ba634ace358c713324a6a0395/etc/api/youtube/v3/youtube-api_overrides.yaml#L1) which will override any value within the respective parent file. This might allow to override the type of `RunQueryResponse`, even though I am not sure how it's easily possible to specify an array of these objects within the schema language.

Any PR is of course welcome.

**Comment by Byron** [comment] 2021-04-15 02:09
Maybe you can try again with v2.0.4 or try an entirely different API generator here: http://github.com/google-apis-rs/generator .

As these crates won't change unless there are contributions I am closing this issue. Thanks for your understanding.

**Closed by Byron** 2021-04-15 02:09 UTC
Labels: acknowledged, bug, help wanted, wontfix
